### ISSUE TITLE
question

### ISSUE THREAD

**Issue by bulolo** [hezongkun/admin-back-end#1]
请问这个怎么跑起来。
我是一个写了无数个egg后端的。。但是还是没跑起来。
不知道为啥出来个连接172.17.0.1，但是完全没找到任何 172.17.0.1相关的。config.json也改成了自己数据库
```
WARN 16780 Sequelize Error: Access denied for user 'root'@'172.17.0.1' (using password: NO), sleep 1 seconds to retry...
```

并且我对这个config.json一头雾水。

区分环境配置不是 config.dev.js  config.prod.js吗
然后在里面default见到有配置 redis,但是sequelize相关的数据库配置是在那里？

另外我见代码内 引入了 egg-mysql 和egg-sequelize，而model用的是 model是用的egg-sequelize，是否意味着 本项目没有用到egg-mysql?

另项目未使用egg-jwt而用jsonwebtoken，是因为考虑的权限的校验吗

我自己勉强加了个 exports.sequelize = {}才跑起来，但很疑惑

感谢回复。

**Comment by hezongkun** [comment]
我现在转前端了，很久没弄这个了，晚点儿或者明儿给你一个新的

**Comment by bulolo** [comment]
感谢。等你😍😘

**Comment by hezongkun** [comment]
已更新，配置放config下的local里，之前gitignore忽略上传了。需要redis和mysql数据库。
swagger可以参考egg-swagger-doc。
sequelize参考egg-sequelize-auto。

**Comment by bulolo** [comment]
感谢，fontend 如果有更新也感谢更新哈😘

**Comment by hezongkun** [comment]
过段时间吧，最近比较忙

**Comment by bulolo** [comment]
新更新的和admin-front-end菜单配合不起来了。估计是接口改动了。😭
![image](https://user-images.githubusercontent.com/10026498/97783934-f528ae00-1bd5-11eb-85e4-a7333c5ab34d.png)

**Comment by bulolo** [comment]
@hezongkun 你好。我详细看了下这个项目最新更新的。写得挺好的，最近看了网上非常多。
希望能更新下前端部分，好能匹配现在的后端。
非常感谢。如果没有时间，可否发我一份最新的前端，即使不完善的，我自行修改。
希望我能联系上你，我的微信:bulolo

**Comment by hezongkun** [comment]
非常抱歉，最近一直在加班，实在没时间弄，留个邮箱，后续如果有可以发给你

**Comment by bulolo** [comment]
> 非常抱歉，最近一直在加班，实在没时间弄，留个邮箱，后续如果有可以发给你

82607314@qq.com

**Comment by tangkepeng** [comment]
> > 非常抱歉，最近一直在加班，实在没时间弄，留个邮箱，后续如果有可以发给你
> 
> [82607314@qq.com](mailto:82607314@qq.com)

你拿到最新的了吗？ @hezongkun 能把这个项目最新的前端、后端发我一份吗？ 429062670@qq.com 感谢

**Comment by bulolo** [comment]
未收到。前端用ant vue pro 后端egg自己重写了

**Comment by hezongkun** [comment]
> 未收到。前端用ant vue pro 后端egg自己重写了

这个项目我应该不会维护了，vue ant design用了2年了，实际使用中项目越大性能越低下   特别是那个table，500条数据就能卡死，而且pro也要收费了，旧版本不会迭代了。建议找找其他框架   比如element-ui   table单独使用[vxe-table](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/start/use)，丑点儿无所谓  性能更高。
还有egg  如果有机会 还是换成[nestjs](https://docs.nestjs.cn。)吧。以后阿里出的东西   我应该会慎用。
